name: widgetbook_onboarding_demo
description: Demonstrates how to use the widgetbook package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Currently the main branch is used to include some fixes.
  # TODO: replace with the latest stable version.
  widgetbook:
    git:
      url: https://github.com/widgetbook/widgetbook.git
      path: packages/widgetbook
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
